# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-08 15:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sandbox_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('api_keys', models.CharField(max_length=100, unique=True)),
                ('api_secret', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('call_back_url', models.URLField(blank=True)),
                ('confirmation_code', models.CharField(max_length=100)),
                ('account_status', models.CharField(default='inactive', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sandbox_users',
                'ordering': ['date'],
                'verbose_name': 'sandbox_user',
            },
        ),
    ]
